// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkiyuphvbqutohmtcuzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhraXl1cGh2YnF1dG9obXRjdXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDM4NTksImV4cCI6MjA2NzExOTg1OX0.hQL-LCSLNcV4Bc7xLGDppYDbNufFJ9yPQfoLGlgBloc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});